### ISSUE TITLE
Redirect every request to HTTPS 

### ISSUE THREAD

**Issue by ulfmagnetics** [apurvis/rader#12]
This will require purchasing an SSL cert on Heroku (or using a self-signed cert)

**Comment by apurvis** [comment]
how much is that?  they have a very small budget but there is at least _some_budget.

**Comment by ulfmagnetics** [comment]
This is what we did for Methodology -- https://elements.heroku.com/addons/sslfasttrack -- it's $14/month and dead simple. There may be other options, but any of the ones I've seen require a static IP address, which costs more than this solution.

**Comment by apurvis** [comment]
is this something we would want to do even if it ended up on TOR?

**Comment by ulfmagnetics** [comment]
[This FAQ](https://riseup.net/en/security/network-security/tor/onionservices-best-practices#ssltls-isnt-necessary) about Tor hidden services suggests that SSL isn't necessary "since it’s a complete encrypted tunnel + PFS (perfect forward secrecy)." So yeah, this would only be necessary if the final site ended up on Heroku. I'll close this one out and can reopen if things end up going that route.
